# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\tangm\Desktop\com\code2\Ui.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(554, 483)
        Form.setStyleSheet(_fromUtf8("background-color:rgb(245, 245, 245)"))
        self.layoutWidget_2 = QtGui.QWidget(Form)
        self.layoutWidget_2.setGeometry(QtCore.QRect(0, 0, 198, 483))
        self.layoutWidget_2.setObjectName(_fromUtf8("layoutWidget_2"))
        self.Debug = QtGui.QVBoxLayout(self.layoutWidget_2)
        self.Debug.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.Debug.setContentsMargins(0, -1, -1, -1)
        self.Debug.setObjectName(_fromUtf8("Debug"))
        self.verticalLayout_18 = QtGui.QVBoxLayout()
        self.verticalLayout_18.setSizeConstraint(QtGui.QLayout.SetMaximumSize)
        self.verticalLayout_18.setObjectName(_fromUtf8("verticalLayout_18"))
        self.distext = QtGui.QTabWidget(self.layoutWidget_2)
        self.distext.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.distext.sizePolicy().hasHeightForWidth())
        self.distext.setSizePolicy(sizePolicy)
        self.distext.setMaximumSize(QtCore.QSize(194, 16777215))
        self.distext.setTabPosition(QtGui.QTabWidget.North)
        self.distext.setTabShape(QtGui.QTabWidget.Triangular)
        self.distext.setUsesScrollButtons(True)
        self.distext.setTabsClosable(False)
        self.distext.setMovable(False)
        self.distext.setObjectName(_fromUtf8("distext"))
        self.dishextext_3 = QtGui.QWidget()
        self.dishextext_3.setMouseTracking(False)
        self.dishextext_3.setObjectName(_fromUtf8("dishextext_3"))
        self.verticalLayout_19 = QtGui.QVBoxLayout(self.dishextext_3)
        self.verticalLayout_19.setMargin(0)
        self.verticalLayout_19.setSpacing(1)
        self.verticalLayout_19.setObjectName(_fromUtf8("verticalLayout_19"))
        self.dishex = QtGui.QPlainTextEdit(self.dishextext_3)
        self.dishex.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Consolas"))
        font.setPointSize(11)
        self.dishex.setFont(font)
        self.dishex.setReadOnly(True)
        self.dishex.setObjectName(_fromUtf8("dishex"))
        self.verticalLayout_19.addWidget(self.dishex)
        self.distext.addTab(self.dishextext_3, _fromUtf8(""))
        self.verticalLayout_18.addWidget(self.distext)
        self.horizontalLayout_27 = QtGui.QHBoxLayout()
        self.horizontalLayout_27.setObjectName(_fromUtf8("horizontalLayout_27"))
        self.qingchuneirong = QtGui.QPushButton(self.layoutWidget_2)
        self.qingchuneirong.setObjectName(_fromUtf8("qingchuneirong"))
        self.horizontalLayout_27.addWidget(self.qingchuneirong)
        self.lingchunwei = QtGui.QPushButton(self.layoutWidget_2)
        self.lingchunwei.setObjectName(_fromUtf8("lingchunwei"))
        self.horizontalLayout_27.addWidget(self.lingchunwei)
        self.verticalLayout_18.addLayout(self.horizontalLayout_27)
        self.line_9 = QtGui.QFrame(self.layoutWidget_2)
        self.line_9.setFrameShape(QtGui.QFrame.HLine)
        self.line_9.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_9.setObjectName(_fromUtf8("line_9"))
        self.verticalLayout_18.addWidget(self.line_9)
        self.Debug.addLayout(self.verticalLayout_18)
        self.verticalLayout_22 = QtGui.QVBoxLayout()
        self.verticalLayout_22.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.verticalLayout_22.setSpacing(3)
        self.verticalLayout_22.setObjectName(_fromUtf8("verticalLayout_22"))
        self.horizontalLayout_28 = QtGui.QHBoxLayout()
        self.horizontalLayout_28.setObjectName(_fromUtf8("horizontalLayout_28"))
        self.portlabel_2 = QtGui.QLabel(self.layoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.portlabel_2.sizePolicy().hasHeightForWidth())
        self.portlabel_2.setSizePolicy(sizePolicy)
        self.portlabel_2.setMinimumSize(QtCore.QSize(60, 0))
        self.portlabel_2.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.portlabel_2.setFont(font)
        self.portlabel_2.setObjectName(_fromUtf8("portlabel_2"))
        self.horizontalLayout_28.addWidget(self.portlabel_2)
        spacerItem = QtGui.QSpacerItem(10, 13, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_28.addItem(spacerItem)
        self.lineEdit_2 = QtGui.QLineEdit(self.layoutWidget_2)
        self.lineEdit_2.setEnabled(False)
        self.lineEdit_2.setMinimumSize(QtCore.QSize(60, 25))
        self.lineEdit_2.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lineEdit_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineEdit_2.setReadOnly(True)
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.horizontalLayout_28.addWidget(self.lineEdit_2)
        self.comport = QtGui.QLineEdit(self.layoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comport.sizePolicy().hasHeightForWidth())
        self.comport.setSizePolicy(sizePolicy)
        self.comport.setMinimumSize(QtCore.QSize(35, 25))
        self.comport.setMaximumSize(QtCore.QSize(40, 16777215))
        self.comport.setMaxLength(2)
        self.comport.setFrame(True)
        self.comport.setEchoMode(QtGui.QLineEdit.Normal)
        self.comport.setAlignment(QtCore.Qt.AlignCenter)
        self.comport.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.comport.setObjectName(_fromUtf8("comport"))
        self.horizontalLayout_28.addWidget(self.comport)
        self.verticalLayout_22.addLayout(self.horizontalLayout_28)
        self.horizontalLayout_29 = QtGui.QHBoxLayout()
        self.horizontalLayout_29.setObjectName(_fromUtf8("horizontalLayout_29"))
        self.bandratelabel_2 = QtGui.QLabel(self.layoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bandratelabel_2.sizePolicy().hasHeightForWidth())
        self.bandratelabel_2.setSizePolicy(sizePolicy)
        self.bandratelabel_2.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.bandratelabel_2.setFont(font)
        self.bandratelabel_2.setObjectName(_fromUtf8("bandratelabel_2"))
        self.horizontalLayout_29.addWidget(self.bandratelabel_2)
        spacerItem1 = QtGui.QSpacerItem(10, 10, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_29.addItem(spacerItem1)
        self.botelv = QtGui.QComboBox(self.layoutWidget_2)
        self.botelv.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.botelv.sizePolicy().hasHeightForWidth())
        self.botelv.setSizePolicy(sizePolicy)
        self.botelv.setMinimumSize(QtCore.QSize(0, 25))
        self.botelv.setMaximumSize(QtCore.QSize(110, 16777215))
        self.botelv.setBaseSize(QtCore.QSize(0, 0))
        self.botelv.setEditable(False)
        self.botelv.setObjectName(_fromUtf8("botelv"))
        self.botelv.addItem(_fromUtf8(""))
        self.botelv.addItem(_fromUtf8(""))
        self.botelv.addItem(_fromUtf8(""))
        self.botelv.addItem(_fromUtf8(""))
        self.botelv.addItem(_fromUtf8(""))
        self.botelv.addItem(_fromUtf8(""))
        self.botelv.addItem(_fromUtf8(""))
        self.botelv.addItem(_fromUtf8(""))
        self.botelv.addItem(_fromUtf8(""))
        self.botelv.addItem(_fromUtf8(""))
        self.botelv.addItem(_fromUtf8(""))
        self.botelv.addItem(_fromUtf8(""))
        self.botelv.addItem(_fromUtf8(""))
        self.botelv.addItem(_fromUtf8(""))
        self.botelv.addItem(_fromUtf8(""))
        self.botelv.addItem(_fromUtf8(""))
        self.botelv.addItem(_fromUtf8(""))
        self.horizontalLayout_29.addWidget(self.botelv)
        self.verticalLayout_22.addLayout(self.horizontalLayout_29)
        self.horizontalLayout_30 = QtGui.QHBoxLayout()
        self.horizontalLayout_30.setObjectName(_fromUtf8("horizontalLayout_30"))
        self.databitlabel_2 = QtGui.QLabel(self.layoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.databitlabel_2.sizePolicy().hasHeightForWidth())
        self.databitlabel_2.setSizePolicy(sizePolicy)
        self.databitlabel_2.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.databitlabel_2.setFont(font)
        self.databitlabel_2.setObjectName(_fromUtf8("databitlabel_2"))
        self.horizontalLayout_30.addWidget(self.databitlabel_2)
        spacerItem2 = QtGui.QSpacerItem(10, 10, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_30.addItem(spacerItem2)
        self.shujuwei = QtGui.QComboBox(self.layoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.shujuwei.sizePolicy().hasHeightForWidth())
        self.shujuwei.setSizePolicy(sizePolicy)
        self.shujuwei.setMinimumSize(QtCore.QSize(0, 25))
        self.shujuwei.setMaximumSize(QtCore.QSize(110, 16777215))
        self.shujuwei.setObjectName(_fromUtf8("shujuwei"))
        self.shujuwei.addItem(_fromUtf8(""))
        self.shujuwei.addItem(_fromUtf8(""))
        self.shujuwei.addItem(_fromUtf8(""))
        self.shujuwei.addItem(_fromUtf8(""))
        self.horizontalLayout_30.addWidget(self.shujuwei)
        self.verticalLayout_22.addLayout(self.horizontalLayout_30)
        self.horizontalLayout_31 = QtGui.QHBoxLayout()
        self.horizontalLayout_31.setObjectName(_fromUtf8("horizontalLayout_31"))
        self.checkbitlabel_2 = QtGui.QLabel(self.layoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkbitlabel_2.sizePolicy().hasHeightForWidth())
        self.checkbitlabel_2.setSizePolicy(sizePolicy)
        self.checkbitlabel_2.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.checkbitlabel_2.setFont(font)
        self.checkbitlabel_2.setObjectName(_fromUtf8("checkbitlabel_2"))
        self.horizontalLayout_31.addWidget(self.checkbitlabel_2)
        spacerItem3 = QtGui.QSpacerItem(10, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_31.addItem(spacerItem3)
        self.jiaoyanwei = QtGui.QComboBox(self.layoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.jiaoyanwei.sizePolicy().hasHeightForWidth())
        self.jiaoyanwei.setSizePolicy(sizePolicy)
        self.jiaoyanwei.setMinimumSize(QtCore.QSize(0, 25))
        self.jiaoyanwei.setMaximumSize(QtCore.QSize(110, 16777215))
        self.jiaoyanwei.setObjectName(_fromUtf8("jiaoyanwei"))
        self.jiaoyanwei.addItem(_fromUtf8(""))
        self.jiaoyanwei.addItem(_fromUtf8(""))
        self.jiaoyanwei.addItem(_fromUtf8(""))
        self.jiaoyanwei.addItem(_fromUtf8(""))
        self.jiaoyanwei.addItem(_fromUtf8(""))
        self.horizontalLayout_31.addWidget(self.jiaoyanwei)
        self.verticalLayout_22.addLayout(self.horizontalLayout_31)
        self.horizontalLayout_32 = QtGui.QHBoxLayout()
        self.horizontalLayout_32.setObjectName(_fromUtf8("horizontalLayout_32"))
        self.stopbitlabel_2 = QtGui.QLabel(self.layoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stopbitlabel_2.sizePolicy().hasHeightForWidth())
        self.stopbitlabel_2.setSizePolicy(sizePolicy)
        self.stopbitlabel_2.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.stopbitlabel_2.setFont(font)
        self.stopbitlabel_2.setObjectName(_fromUtf8("stopbitlabel_2"))
        self.horizontalLayout_32.addWidget(self.stopbitlabel_2)
        spacerItem4 = QtGui.QSpacerItem(10, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_32.addItem(spacerItem4)
        self.tingzhiwei = QtGui.QComboBox(self.layoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tingzhiwei.sizePolicy().hasHeightForWidth())
        self.tingzhiwei.setSizePolicy(sizePolicy)
        self.tingzhiwei.setMinimumSize(QtCore.QSize(0, 25))
        self.tingzhiwei.setMaximumSize(QtCore.QSize(110, 16777215))
        self.tingzhiwei.setObjectName(_fromUtf8("tingzhiwei"))
        self.tingzhiwei.addItem(_fromUtf8(""))
        self.tingzhiwei.addItem(_fromUtf8(""))
        self.tingzhiwei.addItem(_fromUtf8(""))
        self.horizontalLayout_32.addWidget(self.tingzhiwei)
        self.verticalLayout_22.addLayout(self.horizontalLayout_32)
        self.chuankouopen = QtGui.QPushButton(self.layoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chuankouopen.sizePolicy().hasHeightForWidth())
        self.chuankouopen.setSizePolicy(sizePolicy)
        self.chuankouopen.setMaximumSize(QtCore.QSize(194, 16777215))
        self.chuankouopen.setCheckable(True)
        self.chuankouopen.setChecked(False)
        self.chuankouopen.setObjectName(_fromUtf8("chuankouopen"))
        self.verticalLayout_22.addWidget(self.chuankouopen)
        self.Debug.addLayout(self.verticalLayout_22)
        self.debugtab = QtGui.QTabWidget(Form)
        self.debugtab.setEnabled(True)
        self.debugtab.setGeometry(QtCore.QRect(200, 10, 361, 481))
        self.debugtab.setAcceptDrops(False)
        self.debugtab.setAutoFillBackground(False)
        self.debugtab.setStyleSheet(_fromUtf8(""))
        self.debugtab.setTabShape(QtGui.QTabWidget.Triangular)
        self.debugtab.setObjectName(_fromUtf8("debugtab"))
        self.main = QtGui.QWidget()
        self.main.setObjectName(_fromUtf8("main"))
        self.gridLayoutWidget = QtGui.QWidget(self.main)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 351, 81))
        self.gridLayoutWidget.setObjectName(_fromUtf8("gridLayoutWidget"))
        self.gridLayout = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setMargin(0)
        self.gridLayout.setHorizontalSpacing(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.wendu = QtGui.QPlainTextEdit(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wendu.sizePolicy().hasHeightForWidth())
        self.wendu.setSizePolicy(sizePolicy)
        self.wendu.setMidLineWidth(0)
        self.wendu.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.wendu.setObjectName(_fromUtf8("wendu"))
        self.gridLayout.addWidget(self.wendu, 0, 2, 1, 1)
        self.label_11 = QtGui.QLabel(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        self.label_11.setFrameShape(QtGui.QFrame.StyledPanel)
        self.label_11.setTextFormat(QtCore.Qt.AutoText)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout.addWidget(self.label_11, 0, 0, 1, 2)
        self.gridLayoutWidget_2 = QtGui.QWidget(self.main)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(0, 90, 351, 41))
        self.gridLayoutWidget_2.setObjectName(_fromUtf8("gridLayoutWidget_2"))
        self.gridLayout_3 = QtGui.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.settemple = QtGui.QPushButton(self.gridLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.settemple.sizePolicy().hasHeightForWidth())
        self.settemple.setSizePolicy(sizePolicy)
        self.settemple.setObjectName(_fromUtf8("settemple"))
        self.gridLayout_3.addWidget(self.settemple, 0, 0, 1, 1)
        self.temple = QtGui.QLineEdit(self.gridLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.temple.sizePolicy().hasHeightForWidth())
        self.temple.setSizePolicy(sizePolicy)
        self.temple.setObjectName(_fromUtf8("temple"))
        self.gridLayout_3.addWidget(self.temple, 0, 1, 1, 1)
        self.gridLayoutWidget_3 = QtGui.QWidget(self.main)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(0, 180, 351, 271))
        self.gridLayoutWidget_3.setObjectName(_fromUtf8("gridLayoutWidget_3"))
        self.plot = QtGui.QGridLayout(self.gridLayoutWidget_3)
        self.plot.setObjectName(_fromUtf8("plot"))
        self.start = QtGui.QPushButton(self.main)
        self.start.setGeometry(QtCore.QRect(40, 150, 75, 23))
        self.start.setObjectName(_fromUtf8("start"))
        self.stop = QtGui.QPushButton(self.main)
        self.stop.setGeometry(QtCore.QRect(230, 150, 75, 23))
        self.stop.setObjectName(_fromUtf8("stop"))
        self.debugtab.addTab(self.main, _fromUtf8(""))
        self.matplottab_2 = QtGui.QWidget()
        self.matplottab_2.setEnabled(False)
        self.matplottab_2.setObjectName(_fromUtf8("matplottab_2"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.matplottab_2)
        self.verticalLayout_7.setMargin(0)
        self.verticalLayout_7.setSpacing(1)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.Dataplot1_2 = QtGui.QHBoxLayout()
        self.Dataplot1_2.setSpacing(1)
        self.Dataplot1_2.setObjectName(_fromUtf8("Dataplot1_2"))
        self.label = QtGui.QLabel(self.matplottab_2)
        self.label.setObjectName(_fromUtf8("label"))
        self.Dataplot1_2.addWidget(self.label)
        self.verticalLayout_7.addLayout(self.Dataplot1_2)
        self.Dataplot2_2 = QtGui.QHBoxLayout()
        self.Dataplot2_2.setSpacing(1)
        self.Dataplot2_2.setObjectName(_fromUtf8("Dataplot2_2"))
        self.verticalLayout_7.addLayout(self.Dataplot2_2)
        self.Dataplot3_2 = QtGui.QHBoxLayout()
        self.Dataplot3_2.setSpacing(1)
        self.Dataplot3_2.setObjectName(_fromUtf8("Dataplot3_2"))
        self.verticalLayout_7.addLayout(self.Dataplot3_2)
        self.debugtab.addTab(self.matplottab_2, _fromUtf8(""))

        self.retranslateUi(Form)
        self.distext.setCurrentIndex(0)
        self.botelv.setCurrentIndex(12)
        self.debugtab.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "Form", None))
        self.distext.setTabText(self.distext.indexOf(self.dishextext_3), _translate("Form", "Hex", None))
        self.qingchuneirong.setText(_translate("Form", "清除内容", None))
        self.lingchunwei.setText(_translate("Form", "另存为", None))
        self.portlabel_2.setText(_translate("Form", "端口号：", None))
        self.lineEdit_2.setText(_translate("Form", "Com Port", None))
        self.comport.setInputMask(_translate("Form", "99; ", None))
        self.comport.setText(_translate("Form", "3", None))
        self.bandratelabel_2.setText(_translate("Form", "波特率：", None))
        self.botelv.setProperty("currentText", _translate("Form", "9600", None))
        self.botelv.setItemText(0, _translate("Form", "50", None))
        self.botelv.setItemText(1, _translate("Form", "75", None))
        self.botelv.setItemText(2, _translate("Form", "110", None))
        self.botelv.setItemText(3, _translate("Form", "134", None))
        self.botelv.setItemText(4, _translate("Form", "150", None))
        self.botelv.setItemText(5, _translate("Form", "200", None))
        self.botelv.setItemText(6, _translate("Form", "300", None))
        self.botelv.setItemText(7, _translate("Form", "600", None))
        self.botelv.setItemText(8, _translate("Form", "1200", None))
        self.botelv.setItemText(9, _translate("Form", "1800", None))
        self.botelv.setItemText(10, _translate("Form", "2400", None))
        self.botelv.setItemText(11, _translate("Form", "4800", None))
        self.botelv.setItemText(12, _translate("Form", "9600", None))
        self.botelv.setItemText(13, _translate("Form", "19200", None))
        self.botelv.setItemText(14, _translate("Form", "38400", None))
        self.botelv.setItemText(15, _translate("Form", "57600", None))
        self.botelv.setItemText(16, _translate("Form", "115200", None))
        self.databitlabel_2.setText(_translate("Form", "数据位：", None))
        self.shujuwei.setItemText(0, _translate("Form", "8bit", None))
        self.shujuwei.setItemText(1, _translate("Form", "7bit", None))
        self.shujuwei.setItemText(2, _translate("Form", "6bit", None))
        self.shujuwei.setItemText(3, _translate("Form", "5bit", None))
        self.checkbitlabel_2.setText(_translate("Form", "校验位：", None))
        self.jiaoyanwei.setItemText(0, _translate("Form", "None无", None))
        self.jiaoyanwei.setItemText(1, _translate("Form", "Even偶", None))
        self.jiaoyanwei.setItemText(2, _translate("Form", "Odd奇", None))
        self.jiaoyanwei.setItemText(3, _translate("Form", "Mark1", None))
        self.jiaoyanwei.setItemText(4, _translate("Form", "Space0", None))
        self.stopbitlabel_2.setText(_translate("Form", "停止位：", None))
        self.tingzhiwei.setItemText(0, _translate("Form", "1bit", None))
        self.tingzhiwei.setItemText(1, _translate("Form", "1.5bit", None))
        self.tingzhiwei.setItemText(2, _translate("Form", "2bit", None))
        self.chuankouopen.setText(_translate("Form", "打开", None))
        self.wendu.setPlainText(_translate("Form", "None", None))
        self.label_11.setText(_translate("Form", "温度(℃)", None))
        self.settemple.setText(_translate("Form", "设置温度", None))
        self.start.setText(_translate("Form", "Begin", None))
        self.stop.setText(_translate("Form", "Stop", None))
        self.debugtab.setTabText(self.debugtab.indexOf(self.main), _translate("Form", "数据", None))
        self.label.setText(_translate("Form", "by Tang (badppg@qq.com)", None))
        self.debugtab.setTabText(self.debugtab.indexOf(self.matplottab_2), _translate("Form", "About", None))
